// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using CRM.Server.Data;

#nullable disable

namespace CRM.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208123656_UpdateTasksModel")]
    partial class UpdateTasksModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRM.Server.Models.TaskItem", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecurrenceEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecurrenceInterval")
                        .HasColumnType("int");

                    b.Property<int>("RecurrenceType")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TaskId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 100,
                            Description = "Understand client needs and expectations",
                            DueDate = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurring = false,
                            Priority = 3,
                            RecurrenceType = 0,
                            State = 1,
                            Title = "Initial discovery call"
                        },
                        new
                        {
                            TaskId = 2,
                            CreatedAt = new DateTime(2025, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 101,
                            Description = "Send pricing and proposal document",
                            DueDate = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurring = false,
                            Priority = 2,
                            RecurrenceType = 0,
                            State = 2,
                            Title = "Prepare quotation"
                        },
                        new
                        {
                            TaskId = 3,
                            CompletedAt = new DateTime(2025, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 102,
                            Description = "Confirm next meeting and timelines",
                            DueDate = new DateTime(2025, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurring = false,
                            Priority = 1,
                            RecurrenceType = 0,
                            State = 3,
                            Title = "Follow-up call"
                        },
                        new
                        {
                            TaskId = 4,
                            CreatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 103,
                            Description = "Share final agreement via email",
                            DueDate = new DateTime(2025, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurring = false,
                            Priority = 3,
                            RecurrenceType = 0,
                            State = 1,
                            Title = "Send agreement"
                        },
                        new
                        {
                            TaskId = 5,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 104,
                            Description = "Regular monthly feedback call",
                            DueDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurring = true,
                            Priority = 2,
                            RecurrenceEndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecurrenceInterval = 1,
                            RecurrenceType = 3,
                            State = 1,
                            Title = "Monthly check-in"
                        },
                        new
                        {
                            TaskId = 6,
                            CreatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 105,
                            Description = "Track service progress and issues",
                            DueDate = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecurring = true,
                            Priority = 4,
                            RecurrenceEndDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecurrenceInterval = 1,
                            RecurrenceType = 2,
                            State = 2,
                            Title = "Weekly support meeting"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
