// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using CRM.Server.Data;

#nullable disable

namespace CRM.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208120213_SeedTasks")]
    partial class SeedTasks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRM.Server.Models.TaskItem", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            CreatedAt = new DateTime(2025, 12, 8, 12, 2, 13, 111, DateTimeKind.Utc).AddTicks(6849),
                            CustomerId = 100,
                            Description = "Talk about requirements",
                            DueDate = new DateTime(2025, 12, 13, 12, 2, 13, 111, DateTimeKind.Utc).AddTicks(6843),
                            IsCompleted = false,
                            Title = "Initial client meeting"
                        },
                        new
                        {
                            TaskId = 2,
                            CreatedAt = new DateTime(2025, 12, 8, 12, 2, 13, 111, DateTimeKind.Utc).AddTicks(6851),
                            CustomerId = 101,
                            Description = "Send cost estimation",
                            DueDate = new DateTime(2025, 12, 15, 12, 2, 13, 111, DateTimeKind.Utc).AddTicks(6850),
                            IsCompleted = false,
                            Title = "Prepare quotation"
                        },
                        new
                        {
                            TaskId = 3,
                            CompletedAt = new DateTime(2025, 12, 8, 12, 2, 13, 111, DateTimeKind.Utc).AddTicks(6852),
                            CreatedAt = new DateTime(2025, 12, 7, 12, 2, 13, 111, DateTimeKind.Utc).AddTicks(6856),
                            CustomerId = 102,
                            Description = "Confirm next meeting",
                            DueDate = new DateTime(2025, 12, 10, 12, 2, 13, 111, DateTimeKind.Utc).AddTicks(6855),
                            IsCompleted = true,
                            Title = "Follow-up call"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
